## Part 1: Preprocessing

In [202]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [203]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [204]:
# Create y_df with the Attrition and Department columns
y_df=attrition_df[["Attrition","Department"]]


In [205]:
# Create a list of at least 10 column names to use as X data
X_data=["Education","Age","DistanceFromHome","JobSatisfaction","OverTime",'StockOptionLevel','WorkLifeBalance','YearsAtCompany','YearsSinceLastPromotion','NumCompaniesWorked']



# Create X_df using your selected columns

X_df=attrition_df[X_data]
# Show the data types for X_df
X_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Education                1470 non-null   int64 
 1   Age                      1470 non-null   int64 
 2   DistanceFromHome         1470 non-null   int64 
 3   JobSatisfaction          1470 non-null   int64 
 4   OverTime                 1470 non-null   object
 5   StockOptionLevel         1470 non-null   int64 
 6   WorkLifeBalance          1470 non-null   int64 
 7   YearsAtCompany           1470 non-null   int64 
 8   YearsSinceLastPromotion  1470 non-null   int64 
 9   NumCompaniesWorked       1470 non-null   int64 
dtypes: int64(9), object(1)
memory usage: 115.0+ KB


In [206]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_df,y_df,random_state=4)


In [207]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

#new_coder=OneHotEncoder(sparse_output=False)
#new_coder.fit(X_train[["OverTime"]])
#train_data1=new_coder.transform(X_train[["OverTime"]])
#test_data1=new_coder.transform(X_test[["OverTime"]])
#train_data1
def over_time_one(feature):
    converted=[]
    for i in feature:
        if i == "Yes":
            a=1
        else:
            a=0
        converted.append(a)
    return converted
X_train["OverTime"]=over_time_one(X_train["OverTime"])
X_test["OverTime"]=over_time_one(X_test["OverTime"])

In [208]:
X_train["OverTime"].value_counts()

0    787
1    315
Name: OverTime, dtype: int64

In [209]:
# Create a StandardScaler
initiated=StandardScaler()

# Fit the StandardScaler to the training data
initiated.fit(X_train)

# Scale the training and testing data
X_train=initiated.transform(X_train)
X_test=initiated.transform(X_test)
X_train


array([[-0.90293476,  1.6918935 , -0.39088276, ...,  0.49219092,
         1.20023379,  0.12743449],
       [-1.88909344, -0.19555561, -0.14466796, ..., -0.98259746,
        -0.68076782, -0.67047921],
       [ 0.08322392, -0.30658202, -0.02156055, ...,  0.16446017,
         1.51373406, -0.67047921],
       ...,
       [ 0.08322392, -0.63966128,  1.33262089, ..., -0.98259746,
        -0.68076782,  0.12743449],
       [-0.90293476,  0.91470858, -0.63709757, ..., -0.32713596,
        -0.68076782,  0.52639135],
       [ 1.06938259, -0.30658202,  0.10154685, ...,  0.32832554,
         1.51373406, -0.67047921]])

In [210]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder

# Fit the encoder to the training data
encoder_one=OneHotEncoder(sparse_output=False)
encoder_one.fit(y_train[["Department"]])
# Create two new variables by applying the encoder
# to the training and testing data
encoder_two=encoder_one.transform(y_train[["Department"]])
encoder_three=encoder_one.transform(y_test[["Department"]])
encoder_two





array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [211]:
# Create a OneHotEncoder for the Attrition column
attrition_one=OneHotEncoder(sparse_output=False)


# Fit the encoder to the training data
attrition_one.fit(y_train[["Attrition"]])

# Create two new variables by applying the encoder
# to the training and testing data
attrition_two=attrition_one.transform(y_train[["Attrition"]])
attrition_three=attrition_one.transform(y_test[["Attrition"]])
attrition_two


array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

## Create, Compile, and Train the Model

In [213]:
# Find the number of columns in the X training data
X_input=len(X_df.columns)

# Create the input layer
input_layer=layers.Input(shape=(X_input,),name="input_layer")

# Create at least two shared layers
shared_one=layers.Dense(64,activation="relu",name="shared_one")(input_layer)
shared_two=layers.Dense(128,activation="relu",name="shared_two")(shared_one)

In [214]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_layer=layers.Dense(32,activation="relu",name="department_hidden")(shared_two)

# Create the output layer
department_output=layers.Dense(3,activation="softmax",name="department_output")(department_layer)




In [215]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_layer=layers.Dense(32,activation="relu",name="attrition_hidden")(shared_two)

# Create the output layer
attrition_output=layers.Dense(2,activation="sigmoid",name="attrition_output")(attrition_layer)



In [216]:
# Create the model
model=Model(inputs=input_layer,outputs=[department_output,attrition_output])

# Compile the model
model.compile(optimizer="adam",loss={"department_output":"categorical_crossentropy","attrition_output":"binary_crossentropy"},metrics={"department_output":["accuracy"],"attrition_output":["accuracy"]})

# Summarize the model
model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 10)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ shared_one (Dense)            │ (None, 64)                │             704 │ input_layer[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ shared_two (Dense)            │ (None, 128)               │           8,320 │ shared_one[0][0]           │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ department_hidden (Dense)     │ (None, 32)                │           4,128 │ shared_two[0][0]           │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ attrition_hidden (Dense)      │ (None, 32)                │           4,128 │ shared_two[0][0]           │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ department_output (Dense)     │ (None, 3)                 │              99 │ department_hidden[0][0]    │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ attrition_output (Dense)      │ (None, 2)                 │              66 │ attrition_hidden[0][0]     │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [217]:
# Train the model
model.fit(X_train,{"department_output":encoder_two,"attrition_output":attrition_two},epochs=100)


Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - attrition_output_accuracy: 0.6393 - department_output_accuracy: 0.5172 - loss: 1.6103
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8281 - department_output_accuracy: 0.6688 - loss: 1.2280
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8419 - department_output_accuracy: 0.6396 - loss: 1.1978
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8581 - department_output_accuracy: 0.6624 - loss: 1.1249
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8321 - department_output_accuracy: 0.6258 - loss: 1.1892
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8535 - department_output_accuracy: 0.6386 - loss: 1.1032
Epoch 7/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8723 - department_output_accuracy: 0.6314 - loss: 1.1284
Epoch 8/100
35/35 ━━━━━━━━━

In [218]:
# Evaluate the model with the testing data
eval_one=model.evaluate(X_test,{"department_output":encoder_three,"attrition_output":attrition_three})
eval_one

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8287 - department_output_accuracy: 0.5371 - loss: 4.4138  


[4.182013034820557, 0.8260869383811951, 0.5570651888847351]

In [219]:
# Print the accuracy for both department and attrition
list_one=["attrition","department"]
for i,cat in enumerate (list_one):
    print(f"{cat} accuracy: {eval_one [i+1]}")
          

attrition accuracy: 0.8260869383811951
department accuracy: 0.5570651888847351


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3. 